/**  @type {import('tailwindcss').Config} */
const withMT = require("@material-tailwind/react/utils/withMT");
module.exports = withMT({
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        black1: "#111111",
        black2: "#222222",
        black3: "#333333",
        whiteSmoke: "#f5f5f5",
        whiteBody: "#fefefe",
        navBlack: "#161b22",
        magenta: "#b73a58",
        graySand: "#dbdad9",
        grayLilac: "#d4cacd",
        grayAgathe: "#b3b1a2",
        palePink: "#edcdc3",
        paleKaki: "#2f7779",
        blueAir: "#bfcad6",
        pinkPale: "#d0828c",
        blackNext: "#222222",
        blueDark: "#434f58",
        violetBright: "#653f76",
        rhubard: "#661a24",
        roseBrown: "#825f62",
      },
      spacing: {
        "5vh": "5vh",
        "10vh": "10vh",
        "15vh": "15vh",
        "20vh": "20vh",
        "25vh": "25vh",
        "30vh": "30vh",
        "35vh": "35vh",
        "40vh": "40vh",
        "45vh": "45vh",
        "50vh": "50vh",
        "55vh": "55vh",
        "60vh": "60vh",
        "65vh": "60vh",
        "70vh": "70vh",
        "75vh": "75vh",
        "80vh": "80vh",
        "85vh": "85vh",
        "90vh": "90vh",
        "95vh": "95vh",
      },

      fontFamily: {
        sans: ["var(--font-inter)"],
        mono: ["var(--font-roboto)"],
        chivo: ["var(--font-chivo)"],
        jetbrains: ["var(--font-jetbrains)"],
        lobster: ["var(--font-lobster)"],
        baskerville: ["var(--font-baskerville)"],
        abril: ["var(--font-abril)"],
        bebasNeue: ["var(--font-bebasNeue)"],
        pt: ["var(--font-pt)"],
        quickSand: ["var(--font-quickSand)"],
        raleWay: ["var(--font-raleWay)"],
      },
    },
    plugins: [require("@tailwindcss/forms")],
  },
});
