import SignUpTabs from "@/components/Forms/SignUpTabs";

export const metadata = {
  title: "Inscription",
  description: "Generated by student for the students",
};

export default function SignUp({ params }) {
  return (
    <div className=" bg-black1 ">
      <SignUpTabs userRole={params.userRole} />
    </div>
  );
}
