import SignUpTabs from "@/app/[userRole]/signUp/components/SignUpTabs";

export const metadata = {
  title: "Inscription",
  description: "Generated by student for the students",
};

export default function SignUp({ params }) {
  return (
    <div className=" bg-whiteSmoke shadows-text ">
      <SignUpTabs userRole={params.userRole} />
    </div>
  );
}
