import LogIn from "@/app/components/Forms/LogIn";

export const metadata = {
  title: "Login",
  description: "Generated by student for the students",
};

export default function SignIn() {
  return (
    <div>
      <LogIn />
    </div>
  );
}
