import LogIn from "@/app/sign-in/components/Login";

export const metadata = {
  title: "Login",
  description: "Generated by student for the students",
};

export default function SignIn() {
  return (
    <div className="w-screen h-screen">
      <LogIn />
    </div>
  );
}
