import { inter, roboto, chivo, jetBrains, lobster } from "@/assets/font";
import "@/assets/globals.css";

import Footer from "@/components/Footer/Footer";
import NavBar from "@/components/Header/NavBar";
import getUser from "@/FetchFunctions/GET/getUser";

export const metadata = {
  title: "StageSeller",
  description: "Generated by student for the students",
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable} ${chivo.variable} ${jetBrains.variable} ${lobster.variable}`}
    >
      <body className="bg-black1 font-chivo">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
